CREATE TABLE IF NOT EXISTS users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(100)                            NOT NULL,
    surname VARCHAR(100)                            NOT NULL,
    age     INT                                     NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
    );